kind: ManifestRender
metadata:
  name: glooMeshIngress
manifest: |
  apiVersion: supergloo.solo.io/v1
  kind: MeshIngress
  metadata:
    name: gloo
    namespace: {{ .Custom.SuperglooNamespace }}
  spec:
    gloo: {}
    installationNamespace: {{ .InstallNamespace }}
    meshes:
    - name: {{ .MeshRef.Name }}
      namespace: {{ .MeshRef.Namespace }}
